name = "KNITRO"
uuid = "67920dd8-b58e-52a8-8622-53c4cffbe346"
authors = ["Artelys", "JuliaOpt"]
version = "0.6.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MathProgBase = "fdba3010-5040-5b88-9595-932c9decdf73"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "^1"
JuMP = ">= 0.19"
MathOptInterface = ">= 0.8.4"

[extras]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[targets]
test = ["Test", "JuMP", "Printf"]
