[general]
library_name = "libknitro"
output_file_path = "src/libknitro.jl"
use_julia_native_enum_type = true
use_deterministic_symbol = true
prologue_file_path = "gen/prologue.jl"

[codegen]
opaque_as_mutable_struct = false
use_ccall_macro = true

[codegen.macro]
macro_mode = "basic"
