[general]
library_name = "libknitro"
output_file_path = "../src/libknitro.jl"
use_julia_native_enum_type = true
use_deterministic_symbol = true
prologue_file_path = "./prologue.jl"

[codegen]
opaque_as_mutable_struct = false

[codegen.macro]
macro_mode = "basic"
